use_default_settings: true

general:
  instance_name: "searxng"

search:
  autocomplete: "google"
  formats:
    - html
    - json

server:
  secret_key: "secret_key"

engines:
  - name: wolframalpha
    disabled: false
