use_default_settings: true

general:
  instance_name: "searxng"

search:
  autocomplete: "google"
  formats:
    - html
    - json

server:
  secret_key: "secret_key"
  limiter: false
  http_protocol_version: "1.1"

outgoing:
  request_timeout: 3.0
  max_request_timeout: 5.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

engines:
  - name: wolframalpha
    disabled: false
